/* 
 * THIS IS AN UNPUBLISHED WORK CONTAINING D2 TECHNOLOGIES, INC. CONFIDENTIAL  
 * AND PROPRIETARY INFORMATION.  IF PUBLICATION OCCURS, THE FOLLOWING NOTICE  
 * APPLIES: "COPYRIGHT 2004-2009 D2 TECHNOLOGIES, INC. ALL RIGHTS RESERVED"  
 *  
 * $D2Tech$ $Rev: 4321 $ $Date: 2007-10-08 13:53:12 -0400 (Mon, 08 Oct 2007) $
 */


#ifndef _OSAL_CONSTANT_H_
#define _OSAL_CONSTANT_H_

#ifdef __cplusplus
extern "C" {
#endif

#define OSAL_NO_WAIT        (0)
#define OSAL_WAIT_FOREVER   (~0)

typedef enum OSAL_Status {
    OSAL_FAIL = 0,
    OSAL_SUCCESS = 1
} OSAL_Status;

typedef enum OSAL_Boolean {
    OSAL_FALSE = 0,
    OSAL_TRUE = 1
} OSAL_Boolean;

/*
 * NULL pointer
 */
#ifndef NULL
#define NULL (void *)0
#endif

/*
 * Define vPort module id.
 */
typedef enum {
    OSAL_MODULE_NONE,
    OSAL_MODULE_REV_ONLY,

    OSAL_MODULE_AUDIO_VE,
    OSAL_MODULE_VIDEO_VE,

    OSAL_MODULE_CSM_PUBLIC,     /* Other modules to CSM and CSM output event */
    OSAL_MODULE_CSM_PRIVATE,    /* CSM internal */
    OSAL_MODULE_ISIM,
    OSAL_MODULE_MGT,

    OSAL_MODULE_ISI,
    OSAL_MODULE_ISI_MSG_RECV,
    OSAL_MODULE_ISI_RPC_CLIENT,
    OSAL_MODULE_ISI_RPC_SERVER,
    OSAL_MODULE_MC,
    OSAL_MODULE_GAPP,
    OSAL_MODULE_GAPP_GSM,
    OSAL_MODULE_SAPP,
    OSAL_MODULE_MSRP,

    OSAL_MODULE_RIR,
    OSAL_MODULE_SR,
    OSAL_MODULE_VIER,
    OSAL_MODULE_VPR,
    OSAL_MODULE_VPR_KERNEL,

    OSAL_MODULE_SIP,
    OSAL_MODULE_GBAM,
    OSAL_MODULE_SIT,
    OSAL_MODULE_XCAP,

    OSAL_MODULE_VAPP,
    OSAL_MODULE_CSM_UT_CLI,
    OSAL_MODULE_OSAL_UT,
    OSAL_MODULE_TAPP,
    OSAL_MODULE_MM,
    OSAL_MODULE_MM_UT,
    OSAL_MODULE_PRXY,
    OSAL_MODULE_HTTP,
} OSAL_MODULE_ID;

typedef enum {
    OSAL_DATA_STRUCT_UNKONOWN,

    OSAL_DATA_STRUCT_CSM_InputEvent,
    OSAL_DATA_STRUCT_CSM_PrivateInputEvt,
    OSAL_DATA_STRUCT_CSM_OutputEvent,
    OSAL_DATA_STRUCT_ISIP_Message,
    OSAL_DATA_STRUCT_ISI_EventMessage,
    OSAL_DATA_STRUCT_tSipIpcMsg,
    OSAL_DATA_STRUCT_SAPP_TmrEvent,
    OSAL_DATA_STRUCT_MSRP_CmdTaskTmr,
    OSAL_DATA_STRUCT_MSRP_Event,
    OSAL_DATA_STRUCT_MSRP_Cmd,
    OSAL_DATA_STRUCT_MSRP_CmdHdr,
    OSAL_DATA_STRUCT_GSM_Event,
    OSAL_DATA_STRUCT_ISI_ServerEvent,
    OSAL_DATA_STRUCT_ISI_DATA,
    OSAL_DATA_STRUCT_XCAP_Cmd,
    OSAL_DATA_STRUCT_XCAP_Evt,
    OSAL_DATA_STRUCT_VPR_Comm,

    OSAL_DATA_STRUCT_RIR_EventMsg,

    OSAL_DATA_STRUCT__VTSP_CmdMsg,
    OSAL_DATA_STRUCT_VTSP_EventMsg,
    OSAL_DATA_STRUCT__VTSP_RtcpCmdMsg,
    OSAL_DATA_STRUCT__VTSP_RtcpEventMsg,
    OSAL_DATA_STRUCT__VTSP_CIDData,
    OSAL_DATA_STRUCT__VTSP_FlowMsg,
    OSAL_DATA_STRUCT__VTSPR_MultiPktMsg,
    OSAL_DATA_STRUCT__VTSPR_MultiDecodedMsg,
    OSAL_DATA_STRUCT__VTSPR_MultiRawMsg,
    OSAL_DATA_STRUCT__VTSPR_MultiCodedMsg,
    OSAL_DATA_STRUCT_VTSP_Stun,
    OSAL_DATA_STRUCT__VC_AppEventMsg,

    OSAL_DATA_STRUCT_JVHW_Command,
    OSAL_DATA_STRUCT_JVHW_PCM_BUFFER,
    OSAL_DATA_STRUCT_JVHW_Message,

    OSAL_DATA_STRUCT_VAPP_Msg,
    OSAL_DATA_STRUCT_VAPP_MgmtEvent,

    OSAL_DATA_STRUCT_SIT_QueueMsg,

    OSAL_DATA_STRUCT_GBA_Command,
    OSAL_DATA_STRUCT_GBA_Event,

    OSAL_DATA_STRUCT_MM_UtMsg,

    OSAL_DATA_STRUCT_String,
    OSAL_DATA_STRUCT_int,
    OSAL_DATA_STRUCT_HTTP_Event,
} OSAL_DATA_STRUCT_ID;

#ifdef __cplusplus
}
#endif

#endif

