
ifeq ($(BOARD_TEE_CONFIG), watchdata)
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := wdtee_armtz.ko
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_RELATIVE_PATH := modules
LOCAL_SRC_FILES := driver/$(LOCAL_MODULE)
include $(BUILD_PREBUILT)

ABS_SRC_DIR := $(abspath $(LOCAL_PATH))/driver
$(LOCAL_PATH)/driver/wdtee_armtz.ko: $(TARGET_PREBUILT_KERNEL) $(wildcard $(ABS_SRC_DIR)/*.c)
	$(MAKE) -C $(ANDROID_PRODUCT_OUT)/obj/KERNEL M=$(ABS_SRC_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) clean
	$(MAKE) -C $(ANDROID_PRODUCT_OUT)/obj/KERNEL M=$(ABS_SRC_DIR) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE)
endif
