/*
 * Copyright (C) 2012 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INCLUDE_SENSORS_SENSORHANDLESYNC_H_
#define INCLUDE_SENSORS_SENSORHANDLESYNC_H_

#include <hardware/sensors.h>
#include "SensorTypePrivate.h"
/*
 * The prefix MUST follow:
 *  SENSOR_TYPE_*.
 *  SENSOR_STRING_TYPE_*.
 *  SENSOR_HANDLE_TYPE_*.
 * */
// #define SUPPORT_VENDOR_A
#ifdef SUPPORT_VENDOR_A
#include "SensorHandleThirdparty.h"
typedef enum {
    SENSOR_HANDLE_META_DATA                   = SENSOR_TYPE_META_DATA,
    SENSOR_HANDLE_ACCELEROMETER               = ACCELEROMETER,
    SENSOR_HANDLE_GEOMAGNETIC_FIELD           = MAGNETIC_FIELD,
    SENSOR_HANDLE_ORIENTATION                 = ORIENTATION,
    SENSOR_HANDLE_GYROSCOPE                   = GYROSCOPE,
    SENSOR_HANDLE_LIGHT                       = LIGHT,
    SENSOR_HANDLE_PRESSURE                    = PRESSURE,
//    SENSOR_HANDLE_TEMPERATURE                 = TEMPERATURE,
    SENSOR_HANDLE_PROXIMITY                   = PROXIMITY,
    SENSOR_HANDLE_GRAVITY                     = GRAVITY,
    SENSOR_HANDLE_LINEAR_ACCELERATION         = LINEAR_ACCELERATION,
    SENSOR_HANDLE_ROTATION_VECTOR             = ROTATION_VECTOR,
    SENSOR_HANDLE_RELATIVE_HUMIDITY           = RELATIVE_HUMIDITY,
    SENSOR_HANDLE_AMBIENT_TEMPERATURE         = AMBIENT_TEMPERATURE,
    SENSOR_HANDLE_MAGNETIC_FIELD_UNCALIBRATED = MAGNETIC_FIELD_UNCALIBRATED,
    SENSOR_HANDLE_GAME_ROTATION_VECTOR        = GAME_ROTATION_VECTOR,
    SENSOR_HANDLE_GYROSCOPE_UNCALIBRATED      = GYROSCOPE_UNCALIBRATED,
    SENSOR_HANDLE_SIGNIFICANT_MOTION          = SIGNIFICANT_MOTION,
    SENSOR_HANDLE_STEP_DETECTOR               = STEP_DETECTOR,
    SENSOR_HANDLE_STEP_COUNTER                = STEP_COUNTER,
    SENSOR_HANDLE_GEOMAGNETIC_ROTATION_VECTOR = GEOMAGNETIC_ROTATION_VECTOR,
    SENSOR_HANDLE_HEART_RATE                  = HEART_RATE,
    SENSOR_HANDLE_TILT_DETECTOR               = TILT_DETECTOR,
    SENSOR_HANDLE_WAKE_GESTURE                = WAKE_GESTURE,
    SENSOR_HANDLE_GLANCE_GESTURE              = GLANCE_GESTURE,
    SENSOR_HANDLE_PICK_UP_GESTURE             = PICK_UP_GESTURE,
    SENSOR_HANDLE_WRIST_TILT_GESTURE          = WRIST_TILT_GESTURE,

    SENSOR_HANDLE_WAKE_UP_BASE = 1000,
    SENSOR_HANDLE_WAKE_UP_ACCELEROMETER               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ACCELEROMETER,
    SENSOR_HANDLE_WAKE_UP_GEOMAGNETIC_FIELD           = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GEOMAGNETIC_FIELD,
    SENSOR_HANDLE_WAKE_UP_ORIENTATION                 = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ORIENTATION,
    SENSOR_HANDLE_WAKE_UP_GYROSCOPE                   = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GYROSCOPE,
    SENSOR_HANDLE_WAKE_UP_LIGHT                       = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_LIGHT,
    SENSOR_HANDLE_WAKE_UP_PRESSURE                    = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_PRESSURE,
//    SENSOR_HANDLE_WAKE_UP_TEMPERATURE                 = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_TEMPERATURE,
    SENSOR_HANDLE_WAKE_UP_PROXIMITY                   = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_PROXIMITY,
    SENSOR_HANDLE_WAKE_UP_GRAVITY                     = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GRAVITY,
    SENSOR_HANDLE_WAKE_UP_LINEAR_ACCELERATION         = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_LINEAR_ACCELERATION,
    SENSOR_HANDLE_WAKE_UP_ROTATION_VECTOR             = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ROTATION_VECTOR,
    SENSOR_HANDLE_WAKE_UP_RELATIVE_HUMIDITY           = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_RELATIVE_HUMIDITY,
    SENSOR_HANDLE_WAKE_UP_AMBIENT_TEMPERATURE         = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_AMBIENT_TEMPERATURE,
    SENSOR_HANDLE_WAKE_UP_MAGNETIC_FIELD_UNCALIBRATED = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_MAGNETIC_FIELD_UNCALIBRATED,
    SENSOR_HANDLE_WAKE_UP_GAME_ROTATION_VECTOR        = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GAME_ROTATION_VECTOR,
    SENSOR_HANDLE_WAKE_UP_GYROSCOPE_UNCALIBRATED      = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GYROSCOPE_UNCALIBRATED,
    SENSOR_HANDLE_WAKE_UP_SIGNIFICANT_MOTION          = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_SIGNIFICANT_MOTION,
    SENSOR_HANDLE_WAKE_UP_STEP_DETECTOR               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_STEP_DETECTOR,
    SENSOR_HANDLE_WAKE_UP_STEP_COUNTER                = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_STEP_COUNTER,
    SENSOR_HANDLE_WAKE_UP_GEOMAGNETIC_ROTATION_VECTOR = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GEOMAGNETIC_ROTATION_VECTOR,
    SENSOR_HANDLE_WAKE_UP_HEART_RATE                  = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_HEART_RATE,
    SENSOR_HANDLE_WAKE_UP_TILT_DETECTOR               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_TILT_DETECTOR,
    SENSOR_HANDLE_WAKE_UP_WAKE_GESTURE                = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_WAKE_GESTURE,
    SENSOR_HANDLE_WAKE_UP_GLANCE_GESTURE              = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GLANCE_GESTURE,
    SENSOR_HANDLE_WAKE_UP_PICK_UP_GESTURE             = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_PICK_UP_GESTURE,
    SENSOR_HANDLE_WAKE_UP_WRIST_TILT_GESTURE          = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_WRIST_TILT_GESTURE,

    /* Add handle for new sensor type */
    SENSOR_HANDLE_DEVICE_PRIVATE_BASE = 2000,
    SENSOR_HANDLE_SHAKE,
    SENSOR_HANDLE_TAP,
    SENSOR_HANDLE_FLIP,
    SENSOR_HANDLE_TWIST,
    SENSOR_HANDLE_POCKET_MODE,
    SENSOR_HANDLE_HAND_UP,
    SENSOR_HANDLE_HAND_DOWN,
    SENSOR_HANDLE_FACE_UP,
    SENSOR_HANDLE_FACE_DOWN,
    SENSOR_HANDLE_PRIVATE_SENSOR_A,
    SENSOR_HANDLE_CONTEXT_AWARENESS,
    SENSOR_HANDLE_VIRTUAL_GYRO,
    SENSOR_HANDLE_AIR_RECOGNITION,
    SENSOR_HANDLE_PDR,

    SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE = 1000,
    SENSOR_HANDLE_WAKE_UP_SHAKE            = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_SHAKE,
    SENSOR_HANDLE_WAKE_UP_TAP              = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_TAP,
    SENSOR_HANDLE_WAKE_UP_FLIP             = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_FLIP,
    SENSOR_HANDLE_WAKE_UP_TWIST            = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_TWIST,
    SENSOR_HANDLE_WAKE_UP_POCKET_MODE      = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_POCKET_MODE,
    SENSOR_HANDLE_WAKE_UP_HAND_UP          = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_HAND_UP,
    SENSOR_HANDLE_WAKE_UP_HAND_DOWN        = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_HAND_DOWN,
    SENSOR_HANDLE_WAKE_UP_FACE_UP          = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_FACE_UP,
    SENSOR_HANDLE_WAKE_UP_FACE_DOWN        = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_FACE_DOWN,
    SENSOR_HANDLE_WAKE_UP_PRIVATE_SENSOR_A = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_PRIVATE_SENSOR_A,
    SENSOR_HANDLE_WAKE_UP_CONTEXT_AWARENESS = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_CONTEXT_AWARENESS,
    SENSOR_HANDLE_WAKE_UP_VIRTUAL_GYRO     = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_VIRTUAL_GYRO,
    SENSOR_HANDLE_WAKE_UP_AIR_RECOGNITION  = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_AIR_RECOGNITION,
    SENSOR_HANDLE_WAKE_UP_PDR              = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_PDR,

    SENSOR_HANDLE_END
}SENSOR_HANDLE_TYPE;

#else /* SUPPORT_VENDOR_A */
typedef enum {
    /*
     * Android Google type begin
     * WARNING: DO NOT CHANGE
     * */
    SENSOR_HANDLE_META_DATA                   = SENSOR_TYPE_META_DATA,                     /*  (0) */
    SENSOR_HANDLE_ACCELEROMETER               = SENSOR_TYPE_ACCELEROMETER,                 /*  (1) */
    SENSOR_HANDLE_GEOMAGNETIC_FIELD           = SENSOR_TYPE_GEOMAGNETIC_FIELD,             /*  (2) */
    SENSOR_HANDLE_ORIENTATION                 = SENSOR_TYPE_ORIENTATION,                   /*  (3) */
    SENSOR_HANDLE_GYROSCOPE                   = SENSOR_TYPE_GYROSCOPE,                     /*  (4) */
    SENSOR_HANDLE_LIGHT                       = SENSOR_TYPE_LIGHT,                         /*  (5) */
    SENSOR_HANDLE_PRESSURE                    = SENSOR_TYPE_PRESSURE,                      /*  (6) */
    SENSOR_HANDLE_TEMPERATURE                 = SENSOR_TYPE_TEMPERATURE,                   /*  (7) */
    SENSOR_HANDLE_PROXIMITY                   = SENSOR_TYPE_PROXIMITY,                     /*  (8) */
    SENSOR_HANDLE_GRAVITY                     = SENSOR_TYPE_GRAVITY,                       /*  (9) */
    SENSOR_HANDLE_LINEAR_ACCELERATION         = SENSOR_TYPE_LINEAR_ACCELERATION,           /* (10) */
    SENSOR_HANDLE_ROTATION_VECTOR             = SENSOR_TYPE_ROTATION_VECTOR,               /* (11) */
    SENSOR_HANDLE_RELATIVE_HUMIDITY           = SENSOR_TYPE_RELATIVE_HUMIDITY,             /* (12) */
    SENSOR_HANDLE_AMBIENT_TEMPERATURE         = SENSOR_TYPE_AMBIENT_TEMPERATURE,           /* (13) */
    SENSOR_HANDLE_MAGNETIC_FIELD_UNCALIBRATED = SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,   /* (14) */
    SENSOR_HANDLE_GAME_ROTATION_VECTOR        = SENSOR_TYPE_GAME_ROTATION_VECTOR,          /* (15) */
    SENSOR_HANDLE_GYROSCOPE_UNCALIBRATED      = SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,        /* (16) */
    SENSOR_HANDLE_SIGNIFICANT_MOTION          = SENSOR_TYPE_SIGNIFICANT_MOTION,            /* (17) */
    SENSOR_HANDLE_STEP_DETECTOR               = SENSOR_TYPE_STEP_DETECTOR,                 /* (18) */
    SENSOR_HANDLE_STEP_COUNTER                = SENSOR_TYPE_STEP_COUNTER,                  /* (19) */
    SENSOR_HANDLE_GEOMAGNETIC_ROTATION_VECTOR = SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,   /* (20) */
    SENSOR_HANDLE_HEART_RATE                  = SENSOR_TYPE_HEART_RATE,                    /* (21) */
    SENSOR_HANDLE_TILT_DETECTOR               = SENSOR_TYPE_TILT_DETECTOR,                 /* (22) */
    SENSOR_HANDLE_WAKE_GESTURE                = SENSOR_TYPE_WAKE_GESTURE,                  /* (23) */
    SENSOR_HANDLE_GLANCE_GESTURE              = SENSOR_TYPE_GLANCE_GESTURE,                /* (24) */
    SENSOR_HANDLE_PICK_UP_GESTURE             = SENSOR_TYPE_PICK_UP_GESTURE,               /* (25) */
    SENSOR_HANDLE_WRIST_TILT_GESTURE          = SENSOR_TYPE_WRIST_TILT_GESTURE,            /* (26) */
    SENSOR_HANDLE_DEVICE_ORIENTATION          = SENSOR_TYPE_DEVICE_ORIENTATION,            /* (27) */
    SENSOR_HANDLE_STATIONARY_DETECT           = SENSOR_TYPE_STATIONARY_DETECT,             /* (29) */
    SENSOR_HANDLE_MOTION_DETECT               = SENSOR_TYPE_MOTION_DETECT,                 /* (30) */
    /*
     * Handle for SENSOR_FLAG_WAKE_UP flag:
     * for details of SENSOR_FLAG_WAKE_UP, please refer to <hardware/sensors.h>, keywords: "Wake up sensors"
     *
     * ex.
     * SENSOR_TYPE_ACCELEROMETER has both a wake-up and a non-wake variant, so SPRD defined two handle:
     *  non-wake: SENSOR_HANDLE_ACCELEROMETER         = SENSOR_TYPE_ACCELEROMETER,
     *  wake-up : SENSOR_HANDLE_WAKE_UP_ACCELEROMETER = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ACCELEROMETER,
     * */
    SENSOR_HANDLE_WAKE_UP_BASE = 0x32,
    SENSOR_HANDLE_WAKE_UP_ACCELEROMETER               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ACCELEROMETER,                /* (1)  */
    SENSOR_HANDLE_WAKE_UP_GEOMAGNETIC_FIELD           = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GEOMAGNETIC_FIELD,            /* (2)  */
    SENSOR_HANDLE_WAKE_UP_ORIENTATION                 = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ORIENTATION,                  /* (3)  */
    SENSOR_HANDLE_WAKE_UP_GYROSCOPE                   = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GYROSCOPE,                    /* (4)  */
    SENSOR_HANDLE_WAKE_UP_LIGHT                       = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_LIGHT,                        /* (5)  */
    SENSOR_HANDLE_WAKE_UP_PRESSURE                    = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_PRESSURE,                     /* (6)  */
    SENSOR_HANDLE_WAKE_UP_TEMPERATURE                 = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_TEMPERATURE,                  /* (7)  */
    SENSOR_HANDLE_WAKE_UP_PROXIMITY                   = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_PROXIMITY,                    /* (8)  */
    SENSOR_HANDLE_WAKE_UP_GRAVITY                     = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GRAVITY,                      /* (9)  */
    SENSOR_HANDLE_WAKE_UP_LINEAR_ACCELERATION         = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_LINEAR_ACCELERATION,          /* (10) */
    SENSOR_HANDLE_WAKE_UP_ROTATION_VECTOR             = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_ROTATION_VECTOR,              /* (11) */
    SENSOR_HANDLE_WAKE_UP_RELATIVE_HUMIDITY           = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_RELATIVE_HUMIDITY,            /* (12) */
    SENSOR_HANDLE_WAKE_UP_AMBIENT_TEMPERATURE         = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_AMBIENT_TEMPERATURE,          /* (13) */
    SENSOR_HANDLE_WAKE_UP_MAGNETIC_FIELD_UNCALIBRATED = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_MAGNETIC_FIELD_UNCALIBRATED,  /* (14) */
    SENSOR_HANDLE_WAKE_UP_GAME_ROTATION_VECTOR        = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GAME_ROTATION_VECTOR,         /* (15) */
    SENSOR_HANDLE_WAKE_UP_GYROSCOPE_UNCALIBRATED      = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GYROSCOPE_UNCALIBRATED,       /* (16) */
    SENSOR_HANDLE_WAKE_UP_SIGNIFICANT_MOTION          = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_SIGNIFICANT_MOTION,           /* (17) */
    SENSOR_HANDLE_WAKE_UP_STEP_DETECTOR               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_STEP_DETECTOR,                /* (18) */
    SENSOR_HANDLE_WAKE_UP_STEP_COUNTER                = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_STEP_COUNTER,                 /* (19) */
    SENSOR_HANDLE_WAKE_UP_GEOMAGNETIC_ROTATION_VECTOR = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GEOMAGNETIC_ROTATION_VECTOR,  /* (20) */
    SENSOR_HANDLE_WAKE_UP_HEART_RATE                  = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_HEART_RATE,                   /* (21) */
    SENSOR_HANDLE_WAKE_UP_TILT_DETECTOR               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_TILT_DETECTOR,                /* (22) */
    SENSOR_HANDLE_WAKE_UP_WAKE_GESTURE                = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_WAKE_GESTURE,                 /* (23) */
    SENSOR_HANDLE_WAKE_UP_GLANCE_GESTURE              = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_GLANCE_GESTURE,               /* (24) */
    SENSOR_HANDLE_WAKE_UP_PICK_UP_GESTURE             = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_PICK_UP_GESTURE,              /* (25) */
    SENSOR_HANDLE_WAKE_UP_WRIST_TILT_GESTURE          = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_WRIST_TILT_GESTURE,           /* (26) */
    SENSOR_HANDLE_WAKE_UP_DEVICE_ORIENTATION          = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_DEVICE_ORIENTATION,           /* (27) */
    SENSOR_HANDLE_WAKE_UP_STATIONARY_DETECT           = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_STATIONARY_DETECT,            /* (29) */
    SENSOR_HANDLE_WAKE_UP_MOTION_DETECT               = SENSOR_HANDLE_WAKE_UP_BASE + SENSOR_HANDLE_MOTION_DETECT,                /* (30) */

    /*
     * Android Google type end
     * WARNING: DO NOT CHANGE
     * */
    /*
     * Add OEMs HANDLE Begin:
     * "MUST match with Sensor TYPE, which defined in <hardware/sensors.h>"
     *     SENSOR_HANDLE_DEVICE_PRIVATE_BASE         = SENSOR_TYPE_DEVICE_PRIVATE_BASE,    0x10000
     * */
    /*
     * ex.
     * SPRD can add "Glass devices": type and stringType MUST be defined in <hardware/sensors.h>
     * type = SENSOR_TYPE_ON_HEAD_DETECTOR (0x10001)
     * stringType = STRING_SENSOR_TYPE_ON_HEAD_DETECTOR ("com.google.glass.onheaddetector")
     * 
     * handle for "Glass devices" should be add:
     * SENSOR_HANDLE_TYPE_DEVICE_PRIVATE_ON_HEAD_DETECTOR   = SENSOR_TYPE_ON_HEAD_DETECTOR,      0x10001
     * */
    SENSOR_HANDLE_DEVICE_PRIVATE_BASE = 0x64,
    SENSOR_HANDLE_SHAKE,
    SENSOR_HANDLE_TAP,
    SENSOR_HANDLE_FLIP,
    SENSOR_HANDLE_TWIST,
    SENSOR_HANDLE_POCKET_MODE,
    SENSOR_HANDLE_HAND_UP,
    SENSOR_HANDLE_HAND_DOWN,
    SENSOR_HANDLE_FACE_UP_DOWN,
    SENSOR_HANDLE_PRIVATE_SENSOR_A,
    SENSOR_HANDLE_CONTEXT_AWARENESS,
    SENSOR_HANDLE_VIRTUAL_GYRO,
    SENSOR_HANDLE_AIR_RECOGNITION,
    SENSOR_HANDLE_PDR,
    SENSOR_HANDLE_FRONT_CAMERA,
    SENSOR_HANDLE_REAR_CAMERA,
    SENSOR_HANDLE_MEDIA_FLIP,

    SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE = 0x32,
    SENSOR_HANDLE_WAKE_UP_SHAKE             = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_SHAKE,
    SENSOR_HANDLE_WAKE_UP_TAP               = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_TAP,
    SENSOR_HANDLE_WAKE_UP_FLIP              = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_FLIP,
    SENSOR_HANDLE_WAKE_UP_TWIST             = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_TWIST,
    SENSOR_HANDLE_WAKE_UP_POCKET_MODE       = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_POCKET_MODE,
    SENSOR_HANDLE_WAKE_UP_HAND_UP           = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_HAND_UP,
    SENSOR_HANDLE_WAKE_UP_HAND_DOWN         = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_HAND_DOWN,
    SENSOR_HANDLE_WAKE_UP_FACE_UP_DOWN      = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_FACE_UP_DOWN,
    SENSOR_HANDLE_WAKE_UP_PRIVATE_SENSOR_A  = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_PRIVATE_SENSOR_A,
    SENSOR_HANDLE_WAKE_UP_CONTEXT_AWARENESS = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_CONTEXT_AWARENESS,
    SENSOR_HANDLE_WAKE_UP_VIRTUAL_GYRO      = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_VIRTUAL_GYRO,
    SENSOR_HANDLE_WAKE_UP_AIR_RECOGNITION   = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_AIR_RECOGNITION,
    SENSOR_HANDLE_WAKE_UP_PDR               = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_PDR,
    SENSOR_HANDLE_WAKE_UP_FRONT_CAMERA      = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_FRONT_CAMERA,
    SENSOR_HANDLE_WAKE_UP_REAR_CAMERA       = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_REAR_CAMERA,
    SENSOR_HANDLE_WAKE_UP_MEDIA_FLIP        = SENSOR_HANDLE_WAKE_UP_DEVICE_PRIVATE_BASE + SENSOR_HANDLE_MEDIA_FLIP,

    /*
     * Add OEMs HANDLE End:
     * "MUST match with Sensor TYPE, which defined in <hardware/sensors.h>"
     * */
    /*
     * Handle for SENSOR_FLAG_WAKE_UP flag End
     * */

    SPECIAL_ID_START = 0xC8,
    META_DATA,
    SYNC_SYS_REAL_TIME,
    MCU_REINITIAL,
    SPECIAL_ID_END,

    SENSOR_HANDLE_END
}SENSOR_HANDLE_TYPE;
#endif /* SUPPORT_VENDOR_A */
#endif  // INCLUDE_SENSORS_SENSORHANDLESYNC_H_
