LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

isp_use2.0:=0
TARGET_BOARD_CAMERA_HAL_VERSION:=HAL3.0
MINICAMERA:=2
TARGET_BOARD_CAMERA_READOTP_METHOD?=0
TARGET_BOARD_SC_IOMMU_PF:=1



include $(LOCAL_PATH)/Camera_test_common.mk

LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE := testdcam
LOCAL_MODULE_TAGS := optional
LOCAL_32_BIT_ONLY := true

include $(BUILD_EXECUTABLE)



include $(CLEAR_VARS)

isp_use2.0:=0
TARGET_BOARD_CAMERA_HAL_VERSION:=HAL1.0
MINICAMERA:=2
TARGET_BOARD_CAMERA_READOTP_METHOD?=0
TARGET_BOARD_SC_IOMMU_PF:=1



include $(LOCAL_PATH)/Camera_test_common.mk

LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE := testdcam1
LOCAL_MODULE_TAGS := optional
LOCAL_32_BIT_ONLY := true

include $(BUILD_EXECUTABLE)