/*
 * Copyright (C) 2008 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "sensors/SensorHandleSync.h"
#include "sensors/SensorConfigFeature.h"

#include "SensorList.h"

static struct sensor_t sSensorList[] = {
#ifdef SENSORHUB_WITH_ACCELEROMETER
        {.name =       "Accelerometer Sensor",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_ACCELEROMETER,
         .type =       SENSOR_TYPE_ACCELEROMETER,
         .maxRange =   RANGE_A,
         .resolution = CONVERT_A,
         .power =      0.17f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Accelerometer Sensor (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_ACCELEROMETER,
         .type =       SENSOR_TYPE_ACCELEROMETER,
         .maxRange =   RANGE_A,
         .resolution = CONVERT_A,
         .power =      0.17f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACCELEROMETER */
#ifdef SENSORHUB_WITH_MAGNETIC
        {.name =       "Magnetic field Sensor",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_GEOMAGNETIC_FIELD,
         .type =       SENSOR_TYPE_MAGNETIC_FIELD,
         .maxRange =   200.0f,
         .resolution = CONVERT_M,
         .power =      5.0f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Magnetic field Sensor (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GEOMAGNETIC_FIELD,
         .type =       SENSOR_TYPE_MAGNETIC_FIELD,
         .maxRange =   200.0f,
         .resolution = CONVERT_M,
         .power =      5.0f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Magnetic Uncalibrated",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_MAGNETIC_FIELD_UNCALIBRATED,
         .type =       SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,
         .maxRange =   200.0f,
         .resolution = CONVERT_M,
         .power =      5.0f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =    100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Magnetic Uncalibrated (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_MAGNETIC_FIELD_UNCALIBRATED,
         .type =       SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,
         .maxRange =   200.0f,
         .resolution = CONVERT_M,
         .power =      5.0f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =    200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_MAGNETIC */
#ifdef SENSORHUB_WITH_LIGHT
        {.name =       "Light Sensor",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_LIGHT,
         .type =       SENSOR_TYPE_LIGHT,
         .maxRange =   10240.0f,
         .resolution = 1.0f,
         .power =      0.15f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =      0,
         .stringType =         NULL,
         .requiredPermission = NULL,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE,
         .reserved =          {}
        },
        {.name =       "Light Sensor (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_LIGHT,
         .type =       SENSOR_TYPE_LIGHT,
         .maxRange =   10240.0f,
         .resolution = 1.0f,
         .power =      0.15f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =      0,
         .stringType =         NULL,
         .requiredPermission = NULL,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE| SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_LIGHT */
#ifdef SENSORHUB_WITH_PROXIMITY
        {.name =       "Proximity Sensor",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_PROXIMITY,
         .type =       SENSOR_TYPE_PROXIMITY,
         .maxRange =   5.0f,
         .resolution = 1.0f,
         .power =      0.15f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =      0,
         .stringType =         NULL,
         .requiredPermission = NULL,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_PROXIMITY */
#ifdef SENSORHUB_WITH_PRESSURE
        {.name =       "Pressure",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_PRESSURE,
         .type =       SENSOR_TYPE_PRESSURE,
         .maxRange =   1.0f,
         .resolution = 1.0f,
         .power =      0.15f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =      0,
         .stringType =         NULL,
         .requiredPermission = NULL,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Pressure (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_PRESSURE,
         .type =       SENSOR_TYPE_PRESSURE,
         .maxRange =   1.0f,
         .resolution = 1.0f,
         .power =      0.15f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =      0,
         .stringType =         NULL,
         .requiredPermission = NULL,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_PRESSURE */
#ifdef SENSORHUB_WITH_GYROSCOPE
        {.name =       "Gyroscope Sensor",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_GYROSCOPE,
         .type =       SENSOR_TYPE_GYROSCOPE,
         .maxRange =   40.0f,
         .resolution = CONVERT_GYRO,
         .power =      6.1f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Gyroscope Sensor (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GYROSCOPE,
         .type =       SENSOR_TYPE_GYROSCOPE,
         .maxRange =   2000.0f,
         .resolution = CONVERT_GYRO,
         .power =      6.1f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Gyroscope Uncalibrated",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_GYROSCOPE_UNCALIBRATED,
         .type =       SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,
         .maxRange =   2000.0f,
         .resolution = CONVERT_GYRO,
         .power =      6.1f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =    100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Gyroscope Uncalibrated (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GYROSCOPE_UNCALIBRATED,
         .type =       SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,
         .maxRange =   2000.0f,
         .resolution = CONVERT_GYRO,
         .power =      6.1f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =    200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Shake",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_SHAKE,
         .type =       SENSOR_TYPE_SPRD_SHAKE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Shake (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_SHAKE,
         .type =       SENSOR_TYPE_SPRD_SHAKE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Twist",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_TWIST,
         .type =       SENSOR_TYPE_SPRD_TWIST,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Twist (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_TWIST,
         .type =       SENSOR_TYPE_SPRD_TWIST,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_GYROSCOPE */
#if defined(SENSORHUB_WITH_ACC_AND_GYRO_AND_MAG) || defined(SENSORHUB_WITH_ACC_AND_GYRO) || defined(SENSORHUB_WITH_ACC_AND_MAG)
        {.name =       "Orientation Sensor",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_ORIENTATION,
         .type =       SENSOR_TYPE_ORIENTATION,
         .maxRange =   360.0f,
         .resolution = 0.1f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Orientation Sensor (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_ORIENTATION,
         .type =       SENSOR_TYPE_ORIENTATION,
         .maxRange =   360.0f,
         .resolution = 0.1f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Gravity",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_GRAVITY,
         .type =       SENSOR_TYPE_GRAVITY,
         .maxRange =   GRAVITY_EARTH,
         .resolution = 0.01,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Gravity (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GRAVITY,
         .type =       SENSOR_TYPE_GRAVITY,
         .maxRange =   GRAVITY_EARTH,
         .resolution = 0.01,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Linear Acceleration",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_LINEAR_ACCELERATION,
         .type =       SENSOR_TYPE_LINEAR_ACCELERATION,
         .maxRange =   RANGE_A,
         .resolution = 0.01,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Linear Acceleration (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_LINEAR_ACCELERATION,
         .type =       SENSOR_TYPE_LINEAR_ACCELERATION,
         .maxRange =   RANGE_A,
         .resolution = 0.01,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Rotation Vector",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_ROTATION_VECTOR,
         .type =       SENSOR_TYPE_ROTATION_VECTOR,
         .maxRange =   1.0f,
         .resolution = 0.000001f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Rotation Vector (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_ROTATION_VECTOR,
         .type =       SENSOR_TYPE_ROTATION_VECTOR,
         .maxRange =   1.0f,
         .resolution = 0.0001f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACC_AND_GYRO_AND_MAG */
#ifdef SENSORHUB_WITH_ACC_AND_GYRO
        {.name =       "Game Rotation Vector",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_GAME_ROTATION_VECTOR,
         .type =       SENSOR_TYPE_GAME_ROTATION_VECTOR,
         .maxRange =   1.0f,
         .resolution = 0.000001f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Game Rotation Vector (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GAME_ROTATION_VECTOR,
         .type =       SENSOR_TYPE_GAME_ROTATION_VECTOR,
         .maxRange =   1.0f,
         .resolution = 0.0001f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Front Camera",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_FRONT_CAMERA,
         .type =       SENSOR_TYPE_SPRD_FRONT_CAMERA,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Front Camera (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_FRONT_CAMERA,
         .type =       SENSOR_TYPE_SPRD_FRONT_CAMERA,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Rear Camera",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_REAR_CAMERA,
         .type =       SENSOR_TYPE_SPRD_REAR_CAMERA,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Rear Camera (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_REAR_CAMERA,
         .type =       SENSOR_TYPE_SPRD_REAR_CAMERA,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACC_AND_GYRO */
#ifdef SENSORHUB_WITH_ACCELEROMETER
        {.name =       "Significant Motion",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_SIGNIFICANT_MOTION,
         .type =       SENSOR_TYPE_SIGNIFICANT_MOTION,
         .maxRange =   1.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   -1,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =      0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Step Detector",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_STEP_DETECTOR,
         .type =       SENSOR_TYPE_STEP_DETECTOR,
         .maxRange =   200.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Step Detector (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_STEP_DETECTOR,
         .type =       SENSOR_TYPE_STEP_DETECTOR,
         .maxRange =   200.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Step Counter",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_STEP_COUNTER,
         .type =       SENSOR_TYPE_STEP_COUNTER,
         .maxRange =   4294967295.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE,
         .reserved =          {}
        },
        {.name =       "Step Counter (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_STEP_COUNTER,
         .type =       SENSOR_TYPE_STEP_COUNTER,
         .maxRange =   4294967295.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Tilt detector",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_TILT_DETECTOR,
         .type =       SENSOR_TYPE_TILT_DETECTOR,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Tilt detector (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_TILT_DETECTOR,
         .type =       SENSOR_TYPE_TILT_DETECTOR,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Wake Gesture",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_WAKE_GESTURE,
         .type =       SENSOR_TYPE_WAKE_GESTURE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Glance Gesture",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GLANCE_GESTURE,
         .type =       SENSOR_TYPE_GLANCE_GESTURE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Pick Gesture",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_PICK_UP_GESTURE,
         .type =       SENSOR_TYPE_PICK_UP_GESTURE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Tap",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_TAP,
         .type =       SENSOR_TYPE_SPRD_TAP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Tap (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_TAP,
         .type =       SENSOR_TYPE_SPRD_TAP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Filp",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_FLIP,
         .type =       SENSOR_TYPE_SPRD_FLIP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Filp (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_FLIP,
         .type =       SENSOR_TYPE_SPRD_FLIP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Face up & down",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_FACE_UP_DOWN,
         .type =       SENSOR_TYPE_SPRD_FACE_UP_DOWN,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE,
         .reserved =          {}
        },
        {.name =       "Face up & down(WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_FACE_UP_DOWN,
         .type =       SENSOR_TYPE_SPRD_FACE_UP_DOWN,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Context awareness",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_CONTEXT_AWARENESS,
         .type =       SENSOR_TYPE_SPRD_CONTEXT_AWARENESS,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE,
         .reserved =          {}
        },
        {.name =       "Context awareness (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_CONTEXT_AWARENESS,
         .type =       SENSOR_TYPE_SPRD_CONTEXT_AWARENESS,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACCELEROMETER */
#ifdef SENSORHUB_WITH_ACC_AND_MAG
        {.name =       "Geomagnetic Rotation Vector",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_GEOMAGNETIC_ROTATION_VECTOR,
         .type =       SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,
         .maxRange =   1.0f,
         .resolution = 0.000001f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   100,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE,
         .reserved =          {}
        },
        {.name =       "Geomagnetic Rotation Vector (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_GEOMAGNETIC_ROTATION_VECTOR,
         .type =       SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,
         .maxRange =   1.0f,
         .resolution = 0.0001f,
         .power =      11.27f,
         .minDelay =   10000,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   200,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =      200000,
         .flags = SENSOR_FLAG_CONTINUOUS_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACC_AND_MAG */
#ifdef SENSORHUB_WITH_ACC_AND_PROX_AND_LIG
        {.name =       "Pocket mode",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_POCKET_MODE,
         .type =       SENSOR_TYPE_SPRD_POCKET_MODE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE,
         .reserved =          {}
        },
        {.name =       "Pocket mode (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_POCKET_MODE,
         .type =       SENSOR_TYPE_SPRD_POCKET_MODE,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACC_AND_PROX_AND_LIG */
#ifdef SENSORHUB_WITH_ACC_AND_PROX
        {.name =       "Hand up",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_HAND_UP,
         .type =       SENSOR_TYPE_SPRD_HAND_UP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Hand up (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_HAND_UP,
         .type =       SENSOR_TYPE_SPRD_HAND_UP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =       "Hand down",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_HAND_DOWN,
         .type =       SENSOR_TYPE_SPRD_HAND_DOWN,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE,
         .reserved =          {}
        },
        {.name =       "Hand down (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_HAND_DOWN,
         .type =       SENSOR_TYPE_SPRD_HAND_DOWN,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
#endif  /* SENSORHUB_WITH_ACC_AND_PROX */
#ifdef SENSORHUB_WITH_ACCELEROMETER
        {.name =       "Media Flip (WAKE_UP)",
         .vendor =     "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =     SENSOR_HANDLE_WAKE_UP_MEDIA_FLIP,
         .type =       SENSOR_TYPE_SPRD_MEDIA_FLIP,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =      0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =   0,
         .stringType =         0,
         .requiredPermission = 0,
         .maxDelay =           0,
         .flags = SENSOR_FLAG_SPECIAL_REPORTING_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =          {}
        },
        {.name =	   "Device Orientation",
         .vendor =	   "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =	   SENSOR_HANDLE_DEVICE_ORIENTATION,
         .type =	   SENSOR_TYPE_DEVICE_ORIENTATION,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =	   0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =	100,
         .stringType =		   0,
         .requiredPermission = 0,
         .maxDelay =		   0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE,
         .reserved =		  {}
        },
        {.name =	   "Device Orientation (WAKE_UP)",
         .vendor =	   "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =	   SENSOR_HANDLE_WAKE_UP_DEVICE_ORIENTATION,
         .type =	   SENSOR_TYPE_DEVICE_ORIENTATION,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =	   0.17f,
         .minDelay =   0,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =	100,
         .stringType =		   0,
         .requiredPermission = 0,
         .maxDelay =		   0,
         .flags = SENSOR_FLAG_ON_CHANGE_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =		  {}
        },
        {.name =	   "Stationary Detect",
         .vendor =	   "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =	   SENSOR_HANDLE_STATIONARY_DETECT,
         .type =	   SENSOR_TYPE_STATIONARY_DETECT,
         .maxRange =   10.0f,
         .resolution = 1.0f,
         .power =	   0.17f,
         .minDelay =   -1,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =	0,
         .stringType =		   0,
         .requiredPermission = 0,
         .maxDelay =		   0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE,
         .reserved =		  {}
        },
        {.name =	   "Stationary Detect (WAKE UP)",
         .vendor =	   "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =	   SENSOR_HANDLE_WAKE_UP_STATIONARY_DETECT,
         .type =	   SENSOR_TYPE_STATIONARY_DETECT,
         .maxRange =   1.0f,
         .resolution = 1.0f,
         .power =	   0.17f,
         .minDelay =   -1,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =	0,
         .stringType =		   0,
         .requiredPermission = 0,
         .maxDelay =		   0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =		  {}
        },
        {.name =       "Motion Detect",
         .vendor =	   "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =	   SENSOR_HANDLE_MOTION_DETECT,
         .type =	   SENSOR_TYPE_MOTION_DETECT,
         .maxRange =   1.0f,
         .resolution = 1.0f,
         .power =	   0.17f,
         .minDelay =   -1,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =	0,
         .stringType =		   0,
         .requiredPermission = 0,
         .maxDelay =		   0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE,
         .reserved =		  {}
        },
        {.name =	   "Motion Detect (WAKE UP)",
         .vendor =	   "Sprd Group Ltd.",
         .version =    SENSOR_VERSION,
         .handle =	   SENSOR_HANDLE_WAKE_UP_MOTION_DETECT,
         .type =	   SENSOR_TYPE_MOTION_DETECT,
         .maxRange =   1.0f,
         .resolution = 1.0f,
         .power =	   0.17f,
         .minDelay =   -1,
         .fifoReservedEventCount = 0,
         .fifoMaxEventCount =	0,
         .stringType =		   0,
         .requiredPermission = 0,
         .maxDelay =		   0,
         .flags = SENSOR_FLAG_ONE_SHOT_MODE | SENSOR_FLAG_WAKE_UP,
         .reserved =		  {}
        },
#endif
};

static shub_drv_cfg_t sSensorDrvCfg[] = {
    {
        .ctlName    = "/sys/class/sprd_sensorhub/sensor_hub/",
        .ctlMode    = 1,
        .drvName    = "SPRDSensor",
        .drvMode    = 1,
        .sensorList = sSensorList,
        .listSize = ARRAY_SIZE(sSensorList),
    },
};

static shub_cfg_t sSensorCfg = {
    .cfgSize = ARRAY_SIZE(sSensorDrvCfg),
    .cfg     = sSensorDrvCfg,
};

/*
 * DO NOT CHANGE
 * */
pshub_cfg_t shubGetDrvConfig(void) {
    return &sSensorCfg;
}

const struct sensor_t * shubGetList(void) {
    return sSensorList;
}

int shubGetListSize(void) {
    return ARRAY_SIZE(sSensorList);
}
