#ifndef __SPRD_VOWIFI_IMS_CONNMAN_CONSTANTS_H__
#define __SPRD_VOWIFI_IMS_CONNMAN_CONSTANTS_H__

#include "nsIImsRegService.h"
#include <string>

using std::string;


BEGIN_VOWIFI_NAMESPACE

static const string MODULE_TAG = "[ImsCM] ";
static string gLogString;

inline const char* _TAG(const string& tag) {
    gLogString = MODULE_TAG + tag;
    return gLogString.c_str();
}

typedef enum {
    WFC_MODE_UNKNOWN            = -1,
    WFC_MODE_CELLULAR_PREFERRED = nsIImsRegHandler::IMS_PROFILE_CELLULAR_PREFERRED,
    WFC_MODE_CELLULAR_ONLY      = nsIImsRegHandler::IMS_PROFILE_CELLULAR_ONLY,
    WFC_MODE_WIFI_PREFERRED     = nsIImsRegHandler::IMS_PROFILE_WIFI_PREFERRED,
    WFC_MODE_WIFI_ONLY          = nsIImsRegHandler::IMS_PROFILE_WIFI_ONLY,
} WFC_MODE;

typedef enum {
    CALL_MODE_NO_CALL,
    CALL_MODE_CS_CALL,
    CALL_MODE_VOLTE_CALL,
    CALL_MODE_VOWIFI_CALL,
} CALL_MODE;

typedef enum {
    VOLTE_PDN_ACTIVE_FAILED,
    VOLTE_PDN_READY,
    VOLTE_PDN_START,
} VOLTE_PDN_STATE;

typedef enum {
    OPERATION_SWITCH_TO_VOWIFI,
    OPERATION_SWITCH_TO_VOLTE,
    OPERATION_HANDOVER_TO_VOWIFI,
    OPERATION_HANDOVER_TO_VOLTE,
    OPERATION_SET_VOWIFI_UNAVAILABLE,
    OPERATION_CANCEL_CURRENT_REQUEST,
    OPERATION_CP_REJECT_SWITCH_TO_VOWIFI,
    OPERATION_CP_REJECT_HANDOVER_TO_VOWIFI,
    OPERATION_RELEASE_VOWIFI_RESOURCE,
} CM_OPERATION_TYPE;

typedef enum {
    MSG_DEFAULT_ID = -1,
    MSG_LOOP_PROCESS,
    MSG_SWITCH_TO_VOWIFI,
    MSG_SWITCH_TO_VOLTE,
    MSG_HANDOVER_TO_VOWIFI,
    MSG_HANDOVER_TO_VOLTE,
    MSG_HANDOVER_TO_VOLTE_BY_TIMER,
    MSG_RELEASE_VOWIFI_RES,
    MSG_VOWIFI_UNAVAILABLE,
    MSG_CANCEL_CURRENT_REQUEST,
    MSG_RECEIVE_NO_RTP,
    MSG_NO_RTP_PING_DONE,
    MSG_PING_PCSCF_ADDRESS,
} CM_OPERATION_MESSAGE_ID;

typedef enum {
    ERROR_DPD_DISCONNECTED = 1,
    ERROR_SIP_TIMEOUT,
    ERROR_SIP_LOGOUT,
    ERROR_SECURITY_REKEY,
    ERROR_EPDG_STOP,
} VOWIFI_STACK_ERROR_TYPE;

typedef enum {
    OPERATOR_NAME_ID_INVALID,
    OPERATOR_NAME_ID_RELIANCE,
    OPERATOR_NAME_ID_DEFAULT = 0xFFFF,
} OPERATOR_NAME_ID;

static const string OPERATOR_NAME_STRING_UNKNOWN    = "unknown";
static const string OPERATOR_NAME_STRING_RELIANCE   = "reliance";

END_VOWIFI_NAMESPACE

#endif
