#ifndef __SPRD_VOWIFI_IMS_CONNMAN_VERSION_INFO_H__
#define __SPRD_VOWIFI_IMS_CONNMAN_VERSION_INFO_H__


BEGIN_VOWIFI_NAMESPACE

const char* STR_VERSION_INFO = "original version";

END_VOWIFI_NAMESPACE

#endif