#ifndef _ALPDAF_ERRCODE_HEADER_
#define _ALPDAF_ERRCODE_HEADER_

/*
PROPRIETARY STATEMENT:
THIS FILE (OR DOCUMENT) CONTAINS INFORMATION CONFIDENTIAL AND
PROPRIETARY TO ALTEK CORPORATION AND SHALL NOT BE REPRODUCED
OR TRANSFERRED TO OTHER FORMATS OR DISCLOSED TO OTHERS.
ALTEK DOES NOT EXPRESSLY OR IMPLIEDLY GRANT THE RECEIVER ANY
RIGHT INCLUDING INTELLECTUAL PROPERTY RIGHT TO USE FOR ANY
SPECIFIC PURPOSE, AND THIS FILE (OR DOCUMENT) DOES NOT
CONSTITUTE A FEEDBACK TO ANY KIND.
*/

#include "alPD.h"

#define alPDAF_ERR_MODULE                   0x76000//483328
#define alPDAF_ERR_CODE                     alGE_ERR_CODE
#define alPDAF_ERR_SUCCESS                  alGE_ERR_SUCCESS
#define alPDAF_ERR_BUFFER_SIZE_TOO_SMALL    (alPDAF_ERR_MODULE+0x00000001) //483329
#define alPDAF_ERR_BUFFER_IS_NULL           (alPDAF_ERR_MODULE+0x00000002) //483330

//PDAF error code

#define alPDAF_ERR_MEMORY_ALLOCATE_FAIL_S1   ( (alPDAF_ERR_MODULE+0x0000003))
#define alPDAF_ERR_MEMORY_ALLOCATE_FAIL_S2   ( (alPDAF_ERR_MODULE+0x0000004))
#define alPDAF_ERR_PDPACKDATA_SETTING_ERROR  ( (alPDAF_ERR_MODULE+0x0000005))
#define alPDAF_ERR_SCENEDETECTION_ERROR      ( (alPDAF_ERR_MODULE+0x0000006))
#define alPDAF_ERR_WITHOUT_ALPDAF_INITIAL	 ( (alPDAF_ERR_MODULE+0x0000007))
#define alPDAF_ERR_AlREADY_ALPDAF_INITIAL	 ( (alPDAF_ERR_MODULE+0x0000008))

#endif	//_ALCM_BINNING_ERRCODE_HEADER_
