LOCAL_SRC_PATH := $(call my-dir)
include $(CLEAR_VARS)

TARGET_MODULE := efuse

TARGET_LIB := $(LOCAL_SRC_PATH)/libsprd$(TARGET_MODULE).a
OUT_DIR := $(TARGET_OUT_INTERMEDIATES)/sec_bsp/$(TARGET_MODULE)
INSTALLED_TARGET_BIN := $(OUT_DIR)/libsprd$(TARGET_MODULE).a

.PHONY: $(TARGET_MODULE) $(TARGET_MODULE)_build $(INSTALLED_TARGET_BIN)

$(TARGET_MODULE): $(INSTALLED_TARGET_BIN)

$(TARGET_MODULE)_build:
	$(info Building sprd $(TARGET_MODULE) module ...)
	$(MAKE) -C $(LOCAL_SRC_PATH)

$(INSTALLED_TARGET_BIN): $(TARGET_MODULE)_build
	$(hide_cmd) cp $(TARGET_LIB) $@
	$(hide_cmd) rm $(TARGET_LIB)
	$(info ### Done with libsprd$(TARGET_MODULE).a install ###)

ALL_DEFAULT_INSTALLED_MODULES += $(INSTALLED_TARGET_BIN)
ALL_MODULES.$(LOCAL_MODULE).INSTALLED += $(INSTALLED_TARGET_BIN)

