/******************************************************************************
 * File name: allib_ae_errcode.h
 * brief	Flicker Lib. related error code.
 * author		Hubert Huang
 *
 * date		2015/10/23
 ******************************************************************************/
#ifndef ALFLICKERLIB_ERR_H_
#define ALFLICKERLIB_ERR_H_



////Error Code
#define AL_FLICKER_SUCCESS                            0x00
#define AL_FLICKERLIB_GLOBAL_ERR_OFFSET               0xA000
#define AL_FLICKERLIB_SETTINGFILE                     (  AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x100 )

#define AL_FLICKERLIB_INVALID_ADDR                    (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x01)
#define AL_FLICKERLIB_MALLOC_FAIL                     (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x02)
#define AL_FLICKERLIB_INIT_FAIL                       (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x03)
#define AL_FLICKERLIB_CLOSE_FAIL                      (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x04)
#define AL_FLICKERLIB_INVALID_PARAM                   (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x05)
#define AL_FLICKERLIB_MISMATCH_STATS_SIZE             (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x06)
#define AL_FLICKERLIB_MAX_SIZE_EXCEEDED               (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x07)
#define AL_FLICKERLIB_INCONSIST_SETDAT                (AL_FLICKERLIB_GLOBAL_ERR_OFFSET + 0x08)

/* for setting file  */
#define AL_FLICKERLIB_INVALID_MAX_SAMPLE_NUM            ( AL_FLICKERLIB_SETTINGFILE + 0x01 )
#define AL_FLICKERLIB_INVALID_DELTA_AVG_MEAN            ( AL_FLICKERLIB_SETTINGFILE + 0x02 )
#define AL_FLICKERLIB_INVALID_DELTA_CENTER_MEAN         ( AL_FLICKERLIB_SETTINGFILE + 0x03 )
#define AL_FLICKERLIB_INVALID_STRONG_LEVEL_TH           ( AL_FLICKERLIB_SETTINGFILE + 0x04 )
#define AL_FLICKERLIB_INVALID_WEAK_LEVEL_TH             ( AL_FLICKERLIB_SETTINGFILE + 0x05 )
#define AL_FLICKERLIB_INVALID_SYMMPARA                  ( AL_FLICKERLIB_SETTINGFILE + 0x06 )
#define AL_FLICKERLIB_INVALID_2NDPARA                   ( AL_FLICKERLIB_SETTINGFILE + 0x07 )
#define AL_FLICKERLIB_INVALID_SAMPLE_NUM                ( AL_FLICKERLIB_SETTINGFILE + 0x08 )
#define AL_FLICKERLIB_INVALID_LINE_TIME                 ( AL_FLICKERLIB_SETTINGFILE + 0x09 )
#define AL_FLICKERLIB_INVALID_RAW_SIZE                  ( AL_FLICKERLIB_SETTINGFILE + 0x10 )
#define AL_FLICKERLIB_INVALID_DEFAULT_FREQ              ( AL_FLICKERLIB_SETTINGFILE + 0x11 )
#define AL_FLICKERLIB_INVALID_BINNING_RATIO             ( AL_FLICKERLIB_SETTINGFILE + 0x12 )
#define AL_FLICKERLIB_INVALID_SCAN_RANGE                ( AL_FLICKERLIB_SETTINGFILE + 0x13 )
#define AL_FLICKERLIB_INVALID_SAMPLE_RANGE              ( AL_FLICKERLIB_SETTINGFILE + 0x14 )
#define AL_FLICKERLIB_INVALID_FLICKER_ENABLE            ( AL_FLICKERLIB_SETTINGFILE + 0x15 )
#define AL_FLICKERLIB_INVALID_FLICKER_ENABLE_DEBUGLOG   ( AL_FLICKERLIB_SETTINGFILE + 0x16 )
#define AL_FLICKERLIB_INVALID_QUEUE_SETTING             ( AL_FLICKERLIB_SETTINGFILE + 0x17 )
#define AL_FLICKERLIB_INVALID_REFERENCEPREVIOUSDATA     ( AL_FLICKERLIB_SETTINGFILE + 0x18 )
#define AL_FLICKERLIB_INVALID_SAMPLE_RATE               ( AL_FLICKERLIB_SETTINGFILE + 0x19 )
#define AL_FLICKERLIB_INVALID_DEVMAXAMPPROX             ( AL_FLICKERLIB_SETTINGFILE + 0x20 )

#endif  //ALFLICKERLIB_ERR_H_